logging:
  level:
    ROOT: INFO
    org.hibernate.SQL: DEBUG
    kz.hr.onboarding: DEBUG

# configure actuator
management:
  endpoints:
    web:
      exposure:
        include: mapping,bus-refresh,bus-env,health,circuitbreakerevents,retry
  endpoint:
    health:
      enabled: true
      show-details: always
  health:
    circuitbreakers:
      enabled: true

# configure spring
spring:
  application:
    name: onboarding-service
  datasource:
    url: jdbc:postgresql://localhost:5432/onboarding
    username: onboarding
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: db.changelog/master.xml
    enabled: false

# configure circuitbreaker
resilience4j:
  circuitbreaker:
    circuit-breaker-aspect-order: 1
    configs:
      default:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 5
        failure-rate-threshold: 50
        minimum-number-of-calls: 2
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        event-consumer-buffer-size: 20
        ignore-exceptions:
          - kz.hr.onboardingservice.service.exceptions.ServiceBadRequestException
    instances:
      accounting-service:
        base-config: default
      security-service:
        base-config: default
      profiler-service:
        base-config: default
  retry:
    retry-aspect-order: 2
    configs:
      default:
        max-attempts: 3
        wait-duration: 10s
        ignore-exceptions:
          - kz.hr.onboardingservice.service.exceptions.ServiceBadRequestException
    instances:
      accounting-service:
        base-config: default
      security-service:
        base-config: default
      profiler-service:
        base-config: default

server:
  port: 0